// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPS.Domain;

namespace TPS.Domain.Migrations
{
    [DbContext(typeof(TPSDbContext))]
    [Migration("20191017050406_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TPS.Domain.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ASCII")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<float>("Latitude");

                    b.Property<float>("Longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("TPS.Domain.CityAttraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("CityAttractions");
                });

            modelBuilder.Entity("TPS.Domain.CustomerTravelPackage", b =>
                {
                    b.Property<int>("CustomerId");

                    b.Property<int>("TravelPackageId");

                    b.Property<string>("Feedback");

                    b.Property<decimal>("SalePrice");

                    b.Property<DateTime>("StartDate");

                    b.Property<int>("VoucherId");

                    b.HasKey("CustomerId", "TravelPackageId");

                    b.HasIndex("TravelPackageId");

                    b.HasIndex("VoucherId");

                    b.ToTable("CustomerTravelPackages");
                });

            modelBuilder.Entity("TPS.Domain.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<int>("CustomerTravelPackageCustomerId");

                    b.Property<int>("CustomerTravelPackageId");

                    b.Property<int>("CustomerTravelPackageTravelPackageId");

                    b.Property<DateTime>("DateTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("PaymentType")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CustomerTravelPackageCustomerId", "CustomerTravelPackageTravelPackageId");

                    b.ToTable("Payments");

                    b.HasDiscriminator<string>("PaymentType").HasValue("Payment");
                });

            modelBuilder.Entity("TPS.Domain.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Forename")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("PersonType")
                        .IsRequired();

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("TravelProviderId");

                    b.HasKey("Id");

                    b.HasIndex("TravelProviderId");

                    b.ToTable("People");

                    b.HasDiscriminator<string>("PersonType").HasValue("Person");
                });

            modelBuilder.Entity("TPS.Domain.TravelPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<decimal>("RRP");

                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("1");

                    b.HasKey("Id");

                    b.ToTable("TravelPackages");
                });

            modelBuilder.Entity("TPS.Domain.TravelPackageCity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId");

                    b.Property<int>("NumberOfDays");

                    b.Property<int>("TravelPackageId");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("TravelPackageId");

                    b.ToTable("TravelPackageCities");
                });

            modelBuilder.Entity("TPS.Domain.TravelPackageCityAttraction", b =>
                {
                    b.Property<int>("CityAttractionId");

                    b.Property<int>("TravelPackageCityId");

                    b.HasKey("CityAttractionId", "TravelPackageCityId");

                    b.HasIndex("TravelPackageCityId");

                    b.ToTable("TravelPackageCityAttractions");
                });

            modelBuilder.Entity("TPS.Domain.TravelProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("TravelProviders");
                });

            modelBuilder.Entity("TPS.Domain.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId");

                    b.Property<string>("Description");

                    b.Property<int>("DiscountPercentage");

                    b.Property<DateTime>("Expires")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("DATEADD(month, 3, GETDATE())");

                    b.Property<bool>("Valid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("TPS.Domain.BitcoinPayment", b =>
                {
                    b.HasBaseType("TPS.Domain.Payment");

                    b.Property<string>("TransactionHashcode");

                    b.HasDiscriminator().HasValue("Bitcoin");
                });

            modelBuilder.Entity("TPS.Domain.CreditCardPayment", b =>
                {
                    b.HasBaseType("TPS.Domain.Payment");

                    b.Property<string>("RecordOfCharge");

                    b.HasDiscriminator().HasValue("CreditCard");
                });

            modelBuilder.Entity("TPS.Domain.PayPalPayment", b =>
                {
                    b.HasBaseType("TPS.Domain.Payment");

                    b.Property<string>("RecordOfCharge")
                        .HasColumnName("PayPalPayment_RecordOfCharge");

                    b.HasDiscriminator().HasValue("PayPal");
                });

            modelBuilder.Entity("TPS.Domain.Customer", b =>
                {
                    b.HasBaseType("TPS.Domain.Person");

                    b.HasDiscriminator().HasValue("Customer");
                });

            modelBuilder.Entity("TPS.Domain.Employee", b =>
                {
                    b.HasBaseType("TPS.Domain.Person");

                    b.HasDiscriminator().HasValue("Employee");
                });

            modelBuilder.Entity("TPS.Domain.CityAttraction", b =>
                {
                    b.HasOne("TPS.Domain.City", "City")
                        .WithMany("Attractions")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TPS.Domain.CustomerTravelPackage", b =>
                {
                    b.HasOne("TPS.Domain.Customer", "Customer")
                        .WithMany("TravelPackages")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TPS.Domain.TravelPackage", "TravelPackage")
                        .WithMany()
                        .HasForeignKey("TravelPackageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TPS.Domain.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TPS.Domain.Payment", b =>
                {
                    b.HasOne("TPS.Domain.CustomerTravelPackage", "CustomerTravelPackage")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerTravelPackageCustomerId", "CustomerTravelPackageTravelPackageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TPS.Domain.Person", b =>
                {
                    b.HasOne("TPS.Domain.TravelProvider", "TravelProvider")
                        .WithMany("People")
                        .HasForeignKey("TravelProviderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TPS.Domain.TravelPackageCity", b =>
                {
                    b.HasOne("TPS.Domain.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TPS.Domain.TravelPackage", "TravelPackage")
                        .WithMany("Cities")
                        .HasForeignKey("TravelPackageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TPS.Domain.TravelPackageCityAttraction", b =>
                {
                    b.HasOne("TPS.Domain.CityAttraction", "CityAttraction")
                        .WithMany("TravelPackageCityAttractions")
                        .HasForeignKey("CityAttractionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TPS.Domain.TravelPackageCity", "TravelPackageCity")
                        .WithMany("TravelPackageCityAttractions")
                        .HasForeignKey("TravelPackageCityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TPS.Domain.Voucher", b =>
                {
                    b.HasOne("TPS.Domain.Customer", "Customer")
                        .WithMany("Vouchers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
